### ISSUE TITLE
`$file` is never assigned

### ISSUE THREAD

**Issue by iainhallam** [sputnick-dev/xmllint#1]
In a previous commit (https://github.com/sputnick-dev/xmllint/commit/33606ea530fc50cbbeaa8c3ff8efc055d102d20e) the assignment of `$file` was removed, but it has still been used since then. Presumably the checks for the value of `$file` will never return true, so will never affect the code path now?

**Comment by sputnick-dev** [comment]
Thanks for reporting

**Comment by sputnick-dev** [comment]
Thanks for reporting
